version: '2'
services:
    chat-app:
        image: chat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://chat-postgresql:5432/chat
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chat-postgresql:
        extends:
            file: postgresql.yml
            service: chat-postgresql
